# Generated by Django 2.0.2 on 2018-02-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webtoon_no', models.IntegerField(default=0)),
                ('episode_no', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(max_length=300)),
                ('rating', models.CharField(max_length=3)),
                ('created_date', models.DateField(verbose_name='published date')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webtoon_no', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='webtoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtoon.Webtoon'),
        ),
    ]
