# Generated by Django 2.0.2 on 2018-02-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0002_episode_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='rating',
            field=models.CharField(max_length=4),
        ),
    ]
